Repository witseie-elen4010/2022-group-lab-013, pull requests merged in 2022-06, with the labels that each got.

#81 Added database sheets and functions for multiplayer
  Private/Script/GameSheet.js
  Private/Script/MoveSheet.js
  Private/Script/databaseHandler.js
Labels: developer-sized-story

#86 Users can create account
  Private/Script/databaseHandler.js
  Public/Script/loginSetup.js
  Public/Script/signup.js
  Routes/landingRoute.js
  Routes/loginroute.js
  landingRoute.js
  main.js
  views/users/homePage.ejs
  views/users/loginPage.ejs
  views/users/signupPage.ejs
Labels: Persistence, Capabilities

#89 29 users can play multiplayer version
  Public/Script/boardScript.js
  Public/Script/inputLetters.js
  Public/Script/multiplayer.js
  Public/Script/multiplayerCooseWordSetup.js
  Public/css/style.css
  Public/partials/board.ejs
  Routes/landingRoute.js
  main.js
  views/users/multiplayerChooseAWord.ejs
  views/users/multiplayerModes.ejs
Labels: Capabilities, developer-sized-story
